#!/usr/bin/env python3
"""audit_goals.py - per-declaration conclusion shape from the Lean kernel.
"""
from __future__ import annotations
import json
import re
import subprocess
import sys
import time
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import goal_audit_fingerprint as gfp

ROOT = Path(__file__).resolve().parent.parent
FORMAL = ROOT / "formal"
DEPGRAPH_PATH = FORMAL / "depgraph.json"
OUT_PATH = FORMAL / "goal_audit.json"
SIDECAR = FORMAL / "goal_audit.fingerprint.json"
AUDIT_TMP = FORMAL / ".audit_goals.lean"
KINDS = ("thm", "def", "axiom")

LEAN_PROLOGUE = r"""
import Lean
import Lean.PrettyPrinter
import Logos

/-!
Temporary goal-shape auditor (generated by scripts/audit_goals.py).
Prints one `GA`-prefixed record block per `Logos` declaration. Deleted by the
generator; never part of the build.

**How the shape is read.** `Meta.forallTelescope` builds the local context and
hands back `Array Expr` of fvars plus a body containing *fvars, never loose
bound variables*. That single choice removes an entire class of failure that a
hand-rolled binder walk cannot avoid:

  * every binder domain that *depends on an earlier binder* (`h : ClaimField s p`)
    still contains loose bvars `#1 #0` in the raw `Expr`. `Meta.isProp` and the
    delaborator both reach `whnf`, and `whnf` **panics** on an out-of-range loose
    bvar. A panic is not a `Lean.Exception`: `try/catch` cannot catch it and it
    aborts the whole `lake env lean` run.
  * `Meta.withLocalDeclsDND` - the variant that reinstalls binder domains verbatim -
    is documented as being "for bringing variables into scope whose types do
    not depend on each other". Binding it to a telescope of dependent binders is
    exactly the case it does not support.
  * `Expr.abstractRange n #[]` asks to abstract `n` levels while supplying zero
    replacements, so it throws on any domain containing a loose bvar.

`forallTelescope` avoids all three: it abstracts each binder against the fvars
already created, so every domain and the body are closed over fvars, and `isProp`
and `ppExpr` are both safe on them. Verified against the 777 structure-generated
declarations in the graph (`mk.noConfusion`, `recOn`, `casesOn`, `mk.injEq`),
which every hand-rolled version rejected.

**Why the shapes are read in `MetaM`.** A head symbol has to name what it
points at: `(non-constant)` for an `fvar` is not a shape, it is a shrug, and the
previous artifact carried 1 290 of them as conjunct heads. Resolving an `fvar`
to its binder name needs the local context, so the readers below are `MetaM`.
This also makes the spines informative: a premise reads as
`GenuineNormativity/3(s,p,q)` rather than as a bare `GenuineNormativity`, which
is what Rule R Level 0 needs - a route's premises must be identifiable as
*the premises the claim is asserted under*, and a head cannot tell
`GenuineNormativity` from `GenuineNormativity'`.
-/

open Lean Meta Elab Command

namespace LogosGoalAudit

/-- Maximum application arguments rendered per spine node. The walk descends into
    every argument at every level, so the cost of one conjunct is
    `MAX_ARGS^FUEL`, not `FUEL`: with the depth alone bounded, a wide constructor
    turns a two-minute audit into a half-hour one. -/
def MAX_ARGS : Nat := 6

/-- Is this `forallE` an implication (`P → Q`) rather than a genuine `∀`?

    `→` elaborates to a `forallE` whose binder carries a **macro-generated
    hygienic numeral name** -- `a._@._internal._hyg.0` -- and *not* the name
    `Arrow`; `P → Q` and `∀ _ : P, Q` are literally the same term to the kernel,
    and only the binder name tells them apart. A `∀` written in the source keeps
    its user name (`s`, `p`, `q`), so an anonymous or numeral binder is exactly
    the implication case. (The cost of this test is that a source-written
    `∀ _, ...` would be read as an implication; no declaration in the corpus does
    that, and `test_goal_audit.py` re-checks the count of `->` conjuncts.)

    This matters because an implication is part of the *claim*. Peeling it as a
    binder reported the antecedents as sorts the claim ranges over -- for
    `ChoiceField s p ¬p → ClaimsCorrect s p → Chooses s p ¬p` the "bound sorts"
    came out as `ClaimsCorrect, ChoiceField, Prop, Subject`, which is a false
    shape for gate G2, not a cosmetic one. -/
def isArrowBinder (n : Name) : Bool :=
  match n with
  | .anonymous => true
  | .num _ _ => true
  | _ => false

/-- User name of a local declaration, hygienic names flattened to `_`.

    Taking an `FVarId` rather than an `Expr` is the point: `LocalContext.getFVar!`
    takes the expression and asserts `fvarId!` on it, so handing it an
    *application* whose head is the variable is a panic, not a lookup. -/
def localDeclName (id : FVarId) : MetaM String := do
  let raw := (← getLCtx).get! id |>.userName.toString
  return if (raw.splitOn "_@").length > 1 || (raw.splitOn "_hyg").length > 1 then "_" else raw

/-- Head symbol of an expression, resolved in the local context. Never prints
    and never `whnf`s, so it is safe on an open expression. This is the symbol
    gate G1 needs to tell Γ's `Subject` from a model's `ModelSubject`. -/
def headSym (e0 : Expr) : MetaM String := do
  -- `.mdata` is consumed once, up front, and the consumed value is used
  -- throughout, so no arm ever sees a `.mdata` wrapper.
  let e := e0.consumeMData
  match e with
  -- `Prop` and `Type` elaborate to `Sort 0` / `Sort 1`, so `getAppFn` sees
  -- `.sort`, not a constant. Naming them matters: gate G2 compares the sorts a
  -- claim ranges over, and `(sort)` there would be a false mismatch.
  | .sort lvl => return (if lvl == .zero then "Prop"
                        else if lvl == .succ .zero then "Type" else "(sort)")
  | .fvar id => return (← localDeclName id)
  | .bvar i => return s!"#{i}"
  | .forallE n _ _ _ => return (if isArrowBinder n then "->" else "∀")
  | .lam _ _ _ _ => return "λ"
  | e =>
    match e.getAppFn with
    | .const n _ =>
      match n with
      | `Prop => return "Prop"
      | `Type => return "Type"
      | _ => return n.toString
    -- The application's *function* may be a local variable: a generated
    -- recursor's conclusion after `forallTelescope` is `motive t`, where
    -- `motive` is a hypothesis. `getAppFn` matches `.fvar id` and the code
    -- must ask for **that** `id`. Passing `e` -- the whole application -- to
    -- `getFVar!` reaches `Lean.Expr.fvarId!` and panics `fvar expected`, once
    -- per recursor, with a backtrace hundreds of frames deep. It is not
    -- catchable by `try/catch`, so it aborts the run outright.
    | .fvar id => return (← localDeclName id)
    | _ => return "(non-constant)"

/-- Depth-bounded structural signature of a proposition: the head constant, its
    arity, and the heads of its arguments, one level in per unit of `fuel`.

    Depth is the whole point. A head-only reader cannot tell
    `Not (RightWrong → Person)` from `Not (Footprint → Being)`, and
    `Logos.AsietyFreedom.rightWrongFactYieldsNoChooser` -- the C294 refutation
    -- is a three-fold negation, so head-only makes it `{Not}` and
    indistinguishable from any other. `fuel` bounds the walk so a
    structure-generated declaration cannot produce an unbounded string. -/
partial def spineOf (e : Expr) (fuel : Nat) : MetaM String := do
  if fuel == 0 then
    return "…"
  else
    let e := e.consumeMData
    let two := e.getAppArgs
    if e.isAppOf ``And then
      return s!"&({← spineOf two[0]! (fuel-1)} , {← spineOf two[1]! (fuel-1)})"
    else if e.isAppOf ``Or then
      return s!"|({← spineOf two[0]! (fuel-1)} , {← spineOf two[1]! (fuel-1)})"
    else if e.isAppOf ``Iff then
      return s!"<->({← spineOf two[0]! (fuel-1)} , {← spineOf two[1]! (fuel-1)})"
    else if e.isAppOf ``Not then
      return s!"!({← spineOf two[0]! (fuel-1)})"
    else if e.isAppOf ``Eq then
      return s!"=({← spineOf two[0]! (fuel-1)} , {← spineOf two[1]! (fuel-1)})"
    else if e.isAppOf ``HEq then
      return s!"=({← spineOf two[1]! (fuel-1)} , {← spineOf two[2]! (fuel-1)})"
    else if e.isAppOf ``Exists then
      -- `Exists α pred`: `two[0]!` is `α` and `two[1]!` is the predicate, so
      -- reading `two[0]!` as the body reported the *bound variable itself* when
      -- `α` happened to be a local -- which is what made
      -- `¬∃ s p q, M s p ∧ M s q` read as `!(?(S).S)`, the variable standing in
      -- for the whole claim.
      let alpha := e.appFn!.appArg!
      let mat := match two[1]!.consumeMData with
        | .lam _ _ b _ => b
        | b => b
      return s!"?({← headSym alpha}).{← spineOf mat (fuel-1)}"
    else
      match e with
      | .forallE n dom body _ =>
        if isArrowBinder n then
          return s!"->({← spineOf dom (fuel-1)} , {← spineOf body (fuel-1)})"
        else
          return s!"∀({← headSym dom}).{← spineOf body (fuel-1)}"
      | _ =>
        if e.isApp then
          -- Breadth is bounded as well as depth. The walk descends into *every*
          -- argument at each level, so with a depth of 4 a single conjunct of an
          -- application of arity `a` costs up to `a^4` `MetaM` calls. A
          -- structure-generated declaration with wide constructors is enough to
          -- make that explode, and it is the reason the audit went from ~2 min to
          -- over half an hour. The cap is a display limit, and truncation is
          -- marked so that a cut spine is distinguishable from a short one.
          let args := e.getAppArgs
          let shown := args.take MAX_ARGS
          let rest := args.drop MAX_ARGS
          let parts ← shown.mapM (fun a => spineOf a (fuel-1))
          let s := String.intercalate ", " parts.toList
          let tail := if rest.isEmpty then "" else ", …"
          return s!"{← headSym e}/{e.getAppNumArgs}({s}{tail})"
        else
          return (← headSym e)

/-- One top-level conjunct of a claim: how it is quantified, what sorts that
    quantifier binds, its head symbol, and its depth-bounded spine. -/
structure Conj where
  quant : String
  sorts : Array String
  head : String
  spine : String
  deriving Inhabited

/-- Per-conjunct structure of a goal, peeling quantifiers as it goes.

    Four things this reader has to get right, each of which an earlier version
    got wrong and the probe caught:

  * **The quantifier is peeled before `And` is tested.** A reader that tested
    `isAppOf ``And` first never split an `And` *underneath* an `Exists` and
    reported the connective `And` as the head: 93 `def`s were affected,
    including `Logos.AsieticChoice.Asiety`, whose body is
    `∃ s : Subject, ∃ p q : Prop, e = EntityOf s ∧ TrueChoice s p q` and which
    therefore read as `valueHeads == ["And"]`. The peeled quantifier is carried
    down to both sub-conjuncts, so `∃ s, (A ∧ B)` reports `A` and `B` as
    `exists` instead of losing the `∃` and reporting two unqualified claims.

  * **An implication is part of the claim, not context.** `P → Q` is a
    `forallE` named `Arrow`, so peeling every `forallE` turned
    `ChoiceField s p ¬p → ClaimsCorrect s p → Chooses s p ¬p` into a claim about
    `Chooses` whose "bound sorts" were `ClaimsCorrect, ChoiceField, Prop,
    Subject` -- the antecedents read as sorts the claim ranges over. Gate G2
    compares sorts, so that is a false shape, not a cosmetic one. An `Arrow` is
    a terminal conjunct here, named `->` and spanned by the spine.

  * **`Exists α fun x => b` contributes one binder, not two.** The domain is
    `α` and the `fun` is the binder; recursing through the lambda as well
    reported every existential's sort twice.

  * **Binders are named, and the spine is built while they are still in scope.**
    Each peeled binder is introduced as a local `fvar` and the body instantiated
    against it, so a spine reads `Chooses/3(s, p, !(p))` rather than
    `Chooses/3(#3, #2, !(#2))` -- the de Bruijn form was a function of *how
    many* binders had been peeled, so two declarations stating one claim under
    differently-ordered binders got different spines. The head and spine are
    computed *inside* the `withLocalDeclD` scope for exactly this reason: an
    expression returned out of that scope refers to locals that no longer
    exist, and `headSym` renders a dangling local as `[anonymous]`.

    The binder telescope is threaded down, not discarded. A reader that kept
    only the matrix reported **no** bound sorts for `∃ s p q, TrueChoice s p q`,
    which left gate G1 clause (2) (reject a model-local binder) with nothing to
    test. -/
partial def conjunctShapes (q0 : String) (e : Expr) : MetaM (List Conj) := do
  match e.consumeMData with
  | .forallE n dom body _ =>
      if isArrowBinder n then
        let arrow := e.consumeMData
        return [{ quant := q0, sorts := #[], head := "->", spine := ← spineOf arrow 4 }]
      else
        withLocalDeclD n dom fun x => do
          let q := if q0 == "plain" then "forall" else q0
          let hd ← headSym dom
          let cs ← conjunctShapes q (body.instantiate1 x)
          return cs.map (fun c => { c with sorts := #[hd] ++ c.sorts })
  | .lam n dom body _ =>
      withLocalDeclD n dom fun x => do
        let hd ← headSym dom
        let cs ← conjunctShapes q0 (body.instantiate1 x)
        return cs.map (fun c => { c with sorts := #[hd] ++ c.sorts })
  -- A `let` is *context*, not claim. `by` blocks and `have` abbreviations
  -- (`have M := …; …`) leave an `Expr.letE` at the head of the goal body, and
  -- `headSym`'s catch-all sees a `letE` rather than a constant or an
  -- application, so the whole theorem read `(non-constant)`. The abbreviation
  -- is introduced as a **real local** (`withLetDecl`) rather than inlined by
  -- substitution: inlining leaves the body referring to an `fvar` that the local
  -- context does not hold, and `headSym`'s `get!` then throws, which is how one
  -- of the 14 survived the first attempt at this fix.
  | .letE n _ val body _ =>
      withLetDecl n (Expr.sort .zero) val fun x =>
        conjunctShapes q0 (body.instantiate1 x)
  | e =>
      if e.isAppOf ``Exists then
        let alpha := e.appFn!.appArg!
        match e.appArg!.consumeMData with
        | .lam n _ body _ =>
            withLocalDeclD n alpha fun x => do
              let q := if q0 == "plain" then "exists" else q0
              let ha ← headSym alpha
              let cs ← conjunctShapes q (body.instantiate1 x)
              return cs.map (fun c => { c with sorts := #[ha] ++ c.sorts })
        | b =>
            return [{ quant := (if q0 == "plain" then "exists" else q0),
                      sorts := #[← headSym alpha],
                      head := ← headSym b, spine := ← spineOf b 4 }]
      else if (e.isAppOf ``And) && (e.getAppArgs.size == 2) then
        let args := e.getAppArgs
        return (← conjunctShapes q0 args[0]!) ++ (← conjunctShapes q0 args[1]!)
      else
        return [{ quant := q0, sorts := #[], head := ← headSym e, spine := ← spineOf e 4 }]

/-- `exists` / `forall` / `not` / `iff` / `app`, read structurally off the goal. -/
partial def tagOf (e : Expr) : String :=
  let e := e.consumeMData
  if e.isAppOf ``Not then "not"
  else if e.isAppOf ``Iff then "iff"
  else if e.isAppOf ``Exists then "exists"
  else match e with
    | .forallE .. => "forall"
    | .mdata _ b => tagOf b
    | _ => "app"

/-- A readable, stable name for a binder.

    `LocalDecl.userName` **is** the hygienic name for an anonymous binder
    (`a._@._internal._hyg.0`, or a `_hygCtx` path for a match arm), so reading it
    is what leaked those names into the artifact: the previous version claimed
    to have fixed this and had not, leaving 771 hypothesis names and 2 084
    `binderFree` entries polluted across 1 533 records. Any name carrying those
    two markers is not an identifier a reader can use, and the binder's identity
    is already carried by its position in `boundSorts` and `conjuncts[].sorts`. -/
def binderName (x : Expr) : MetaM String := do
  match x with
  | .fvar _ =>
    let raw := (← getLCtx).getFVar! x |>.userName.toString
    return if (raw.splitOn "_@").length > 1 || (raw.splitOn "_hyg").length > 1 then "_" else raw
  | _ => return "_"

/-- Accumulate every `Logos.*` constant `e` mentions, structurally. -/
def addRefs (e : Expr) (acc : Array Name) : Array Name :=
  e.getUsedConstants.foldl
    (fun a c => if c.toString.startsWith "Logos." then a.push c else a) acc

def declType : ConstantInfo → Expr
  | .thmInfo i => i.type
  | .axiomInfo i => i.type
  | .defnInfo i => i.type
  | .opaqueInfo i => i.type
  | _ => .sort 0

/-- For a `def`, the spine heads of the body's top-level conjuncts. A definition
    body is nearly always a `lambda`, so the value is handed to `conjunctShapes`
    **directly**: that function peels `.lam`/`.forallE`/`.letE` itself and
    records the sorts each binder ranges over. Peeling first with a dedicated
    `peelBody` and *then* walking the result is what produced the original
    §12b.1 #1 defect — the quantifiers were gone before the walk, so the
    identification inside `∃ s p q, e = EntityOf s ∧ TrueChoice s p q` was split
    as a bare `And`, and on the other side the sorts of `∀ t₁ t₂ : Time, …` were
    discarded while the `Iff` survived, reporting an unquantified biconditional
    that no reader can test. Only ever called for a `def`/`opaque`: a `thm` has
    no value, and the previous version emitted a bogus `valueHeads == ["Prop"]`
    for all 2 836 theorems and axioms by reading `(.sort 0)` off the fallback. -/
def defValueConjuncts (ci : ConstantInfo) : MetaM (List (String × String)) := do
  match ci with
  | .defnInfo i => return (← conjunctShapes "plain" i.value).map (fun c => (c.quant, c.head))
  | .opaqueInfo i => return (← conjunctShapes "plain" i.value).map (fun c => (c.quant, c.head))
  | _ => return []

/-- Emit one declaration's record. `forallTelescope` supplies the binder context,
    so `isProp` and `ppExpr` are called only on fvar-closed expressions. -/
def emit (ci : ConstantInfo) : MetaM Unit := do
  let name := ci.name
  let kind :=
    match ci with
    | .thmInfo _ => "thm"
    | .axiomInfo _ => "axiom"
    | .opaqueInfo _ => "opaque"
    | _ => "def"
  logInfo m!"GA name {name.toString}"
  logInfo m!"GA kind {kind}"
  Meta.forallTelescope (declType ci) fun xs body => do
    -- A binder whose domain is a proposition is a *premise*, not a sort. The
    -- previous version put both in `boundSorts`, so 2 809 records carried
    -- entries that were not sorts at all (`GenuineNormativity`, `Exists`,
    -- `(non-constant)`). Gate G2 compares sorts, so they are separated here.
    let mut sorts : Array String := #[]
    let mut hyps : List (String × String × String) := []
    for x in xs do
      let d ← inferType x
      let nm ← binderName x
      if (← isProp d) then
        hyps := hyps ++ [(nm, ← headSym d, ← spineOf d 2)]
      else
        sorts := sorts.push (← headSym d)
    -- Rendered with an unbounded width *and* newline-escaped. `ppExpr` wraps,
    -- and `logInfo` emitted the wrapped form verbatim, so `logInfo`'s output was
    -- cut at the first line break and the Python side (which reads line by
    -- line) silently kept only that first line. 177 goals were truncated this
    -- way, 31 of them hand-written -- among them `asietic_summary`,
    -- `asietyFreedom_summary`, `master_agency_determinism_synthesis` and
    -- `reductio_frontier_summary`, i.e. exactly the multi-conjunct synthesis
    -- theorems the badge machinery reads. One of them had been "spot-checked"
    -- in the plan with the missing tail filled in by hand.
    let goalFmt ← PrettyPrinter.ppExpr body
    let goal := (String.trimAscii (goalFmt.pretty (width := 1000000))).replace "\n" "\\n"
    logInfo m!"GA goal {goal}"
    logInfo m!"GA goalTag {tagOf body}"
    for (n, h, sp) in hyps do
      logInfo m!"GA hypName {n}"
      logInfo m!"GA hyp {h}"
      logInfo m!"GA hypSpine {sp}"
    for c in ← conjunctShapes "plain" body do
      logInfo m!"GA conjBegin {c.quant}"
      for t in c.sorts do logInfo m!"GA conjSort {t}"
      logInfo m!"GA conjHead {c.head}"
      logInfo m!"GA conjSpine {c.spine}"
      logInfo m!"GA conjEnd"
    for s in sorts do logInfo m!"GA sort {s}"
    for x in xs do logInfo m!"GA free {← binderName x}"
    for (vq, vh) in ← defValueConjuncts ci do logInfo m!"GA value {vq} {vh}"
    -- Every `Logos.*` constant this declaration mentions, collected from the
    -- `Expr` (not from a printed string): goal body, every binder domain, and
    -- the body of a `def`. Python checks this against the environment, which is
    -- the authority -- `depgraph.json` deliberately omits model-local constants
    -- such as `GodAloneModel.Creates`, and that omission is a G1 signal.
    let defBody :=
      match ci with
      | .defnInfo i => i.value
      | .opaqueInfo i => i.value
      | _ => .sort 0
    let mut refs : Array Name := addRefs body #[]
    for x in xs do refs := addRefs (← inferType x) refs
    refs := addRefs defBody refs
    let mut seen : Array Name := #[]
    for c in refs do
      if c ∈ seen then pure () else seen := seen.push c
    seen := seen.qsort (fun a b => a.toString < b.toString)
    for c in seen do logInfo m!"GA ref {c.toString}"
  logInfo m!"GA end"

def run : MetaM Unit := do
  let env ← getEnv
  let mut acc : Array Name := #[]
  for (name, _) in env.constants.toList do
    if name.isInternal then continue
    unless name.toString.startsWith "Logos." do continue
    match env.find? name with
    | some (.thmInfo _) => acc := acc.push name
    | some (.axiomInfo _) => acc := acc.push name
    | some (.defnInfo _) => acc := acc.push name
    | some (.opaqueInfo _) => acc := acc.push name
    | _ => pure ()
  let names := acc.qsort (fun a b => a.toString < b.toString)
  -- Manifest of *every* `Logos.*` constant of *every* kind (structures, ctors,
  -- recursors, instances). A declaration may legitimately mention `S`, `S.mk`,
  -- `S.rec` or `S._sizeOf_inst`, none of which is a thm/def/axiom/opaque and so
  -- none of which is audited. This is what makes the `refs` check below
  -- sound: the authority is the environment, not the audited subset.
  -- No `isInternal` filter here (unlike the audited list): compiler-generated
  -- auxiliaries such as `S._sizeOf_inst` and `S._proof_1` are internal by name
  -- yet are legitimately referenced by a compiled `def`'s body, so excluding
  -- them would make the `refs` check unsound. This list is validation-only.
  let mut manifest : Array Name := #[]
  for (n, _) in env.constants.toList do
    if n.toString.startsWith "Logos." then manifest := manifest.push n
  let manifestSorted := manifest.qsort (fun a b => a.toString < b.toString)
  for n in manifestSorted do logInfo m!"GA manifest {n.toString}"
  logInfo m!"GA manifestEnd {manifestSorted.size}"
  let mut seen : Nat := 0
  let mut failed : Nat := 0
  let t0 ← IO.monoMsNow
  let mut lastBeat := t0
  for name in names do
    let some ci := env.find? name | pure ()
    -- A failure is reported through `logInfo`, never `logError`: `logError`
    -- increments Lean's error counter, and hitting `maxErrors` (100) aborts the
    -- run, so one un-auditable declaration would destroy the whole artifact.
    -- The Python side decides what is fatal (a `thm`/`axiom` that lost its
    -- shape, or a truncated goal), which is where the policy belongs.
    try
      emit ci
      seen := seen + 1
    catch _ =>
      logInfo m!"GA name {name.toString}"
      logInfo m!"GA kind ERROR"
      logInfo m!"GA end"
      failed := failed + 1
    -- Heartbeat. `lake env lean` block-buffers stdout, so a captured pipe shows
    -- nothing until the process exits and an unmeasured run looks like a hang;
    -- four probes were lost to that. These lines are recognised by the Python
    -- wrapper and echoed to *its* stderr as they arrive, and the five slowest
    -- declarations are named, which is what actually localises the cost.
    if seen % 200 == 0 then
      let dt ← IO.monoMsNow
      logInfo m!"GA progress {seen} {dt - t0}"
      if seen % 1000 == 0 then
        let t1 ← IO.monoMsNow
        logInfo m!"GA progressSLOW {seen} {t1 - lastBeat}"
        lastBeat := t1
  logInfo m!"GA count {seen}"
  logInfo m!"GA failed {failed}"
  let tAll ← IO.monoMsNow
  logInfo m!"GA total {tAll - t0}"

run_cmd do liftCoreM (MetaM.run' run)

end LogosGoalAudit
"""

GA_LINE_RE = re.compile(r"^GA\s+(\w+)\s?(.*)$")

_BRACKETS = (("(", ")"), ("[", "]"), ("{", "}"))


def _strip_log_prefix(line: str) -> str:
    """Strip the `lake env lean` `file:line:col: ` / `warning:` chatter."""
    if "GA " not in line:
        return line
    idx = line.find("GA ")
    return line[idx:]


def _truncated(goal: str) -> str | None:
    """Return the bracket left open by a cut-off goal, or `None` if it is whole.

    A `PrettyPrinter` line break used to end the emitted line, so the parser saw
    a prefix and the rest of the expression was lost with no error anywhere.
    Unbalanced brackets are the mechanical signature of that; checking for them
    is what keeps the defect from returning unnoticed.
    """
    for opener, closer in _BRACKETS:
        if goal.count(opener) != goal.count(closer):
            return opener
    return None


def parse_ga(text: str) -> tuple[dict, int | None, list, int, list]:
    """Parse `run_cmd` output -> (records, count, errors, failed, manifest)."""
    records: dict = {}
    manifest: list[str] = []
    cur: dict | None = None
    conj: dict | None = None
    count = None
    errors: list[str] = []
    failed = 0
    for raw in text.splitlines():
        line = _strip_log_prefix(raw).strip()
        m = GA_LINE_RE.match(line)
        if not m:
            continue
        tag, val = m.group(1), m.group(2).strip()
        if tag == "count":
            count = int(val)
            continue
        if tag == "failed":
            failed = int(val)
            continue
        if tag == "ERROR":
            errors.append(val)
            continue
        if tag == "manifest":
            manifest.append(val)
            continue
        if tag == "manifestEnd":
            continue
        if tag == "name":
            cur = {
                "kind": "", "goal": "", "hypothesis": [], "headSyms": [],
                "valueConjuncts": [], "boundSorts": [], "binderFree": [],
                "goalTag": "app", "refs": [], "conjuncts": [],
            }
            conj = None
            records[val] = cur
            continue
        if cur is None:
            continue
        if tag == "end":
            cur = None
            conj = None
        elif tag == "kind":
            cur["kind"] = val
        elif tag == "goal":
            cur["goal"] = val.replace("\\n", "\n")
        elif tag == "goalTag":
            cur["goalTag"] = val
        elif tag == "hypName":
            cur["hypothesis"].append({"binder": val, "head": "", "spine": ""})
        elif tag == "hyp":
            if cur["hypothesis"] and not cur["hypothesis"][-1]["head"]:
                cur["hypothesis"][-1]["head"] = val
        elif tag == "hypSpine":
            if cur["hypothesis"] and not cur["hypothesis"][-1]["spine"]:
                cur["hypothesis"][-1]["spine"] = val
        elif tag == "conjBegin":
            conj = {"quant": val, "sorts": [], "head": "", "spine": ""}
            cur["conjuncts"].append(conj)
        elif tag == "conjSort":
            if conj is not None:
                conj["sorts"].append(val)
        elif tag == "conjHead":
            if conj is not None:
                conj["head"] = val
        elif tag == "conjSpine":
            if conj is not None:
                conj["spine"] = val
        elif tag == "conjEnd":
            conj = None
        elif tag == "value":
            vq, _, vh = val.partition(" ")
            cur["valueConjuncts"].append({"quant": vq, "head": vh})
        elif tag == "ref":
            cur["refs"].append(val)
        elif tag == "sort":
            cur["boundSorts"].append(val)
        elif tag == "free":
            cur["binderFree"].append(val)
    return records, count, errors, failed, manifest


def main() -> int:
    ok_fp, why_fp = gfp.check()
    if ok_fp:
        print(f"goal audit: {why_fp}.")
        return 0
    print(f"goal audit: {why_fp}; regenerating…")

    # Write the prologue to disk *before* launching Lean, and tell Lean to report
    # progress on **stderr** and to a file. `lake env lean` block-buffers stdout,
    # so a backgrounded run shows nothing at all until it exits — three probes
    # were lost to this. The prologue's `emit` is instrumented to `logInfo` a
    # `GA progress <n> <ms>` line every `PROGRESS_EVERY` declarations, and this
    # wrapper re-runs the walk with an unbuffered stderr tee so the wall-clock and
    # the per-stage cost are both visible *while* it runs.
    AUDIT_TMP.write_text(LEAN_PROLOGUE, encoding="utf-8")

    if not DEPGRAPH_PATH.exists():
        print(f"ERROR: {DEPGRAPH_PATH} missing. Run:\n"
              "  cd formal && lake exe depviz --roots Logos --json-out depgraph.json --dot-out depgraph.dot",
              file=sys.stderr)
        return 1

    graph = json.loads(DEPGRAPH_PATH.read_text(encoding="utf-8"))
    nodes = [n for n in graph["nodes"] if n["kind"] in KINDS]
    names = sorted(n["fullName"] for n in nodes)
    graph_names = {n["fullName"] for n in graph["nodes"]}
    print(f"auditing goal shape of {len(names)} declarations …")
    lake = "lake"
    fallback = Path.home() / ".elan" / "bin" / "lake"
    if subprocess.run(["which", "lake"], capture_output=True).returncode != 0 and fallback.exists():
        lake = str(fallback)
    # Stream instead of `capture_output`: Lean block-buffers stdout, so a captured
    # pipe reveals nothing until exit. We merge stderr into the same stream and
    # flush as we go, and the `GA progress` lines the prologue emits land in the
    # log promptly. The 30-minute ceiling is a hang guard, not a budget -- a full
    # run of 6 397 declarations is minutes.
    t0 = time.time()
    proc = subprocess.Popen(
        [lake, "env", "lean", str(AUDIT_TMP)],
        cwd=str(FORMAL), stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )
    collected: list[str] = []
    try:
        assert proc.stdout is not None
        for line in proc.stdout:
            collected.append(line)
            if line.startswith(("GA progress", "GA total", "error:")):
                sys.stderr.write(f"[{time.time() - t0:7.1f}s] {line}")
                sys.stderr.flush()
        proc.wait(timeout=1800 - (time.time() - t0))
    except subprocess.TimeoutExpired:
        proc.kill()
        AUDIT_TMP.unlink(missing_ok=True)
        print(f"ERROR: `lake env lean` exceeded 1800 s ({len(collected)} lines seen).",
              file=sys.stderr)
        return 1
    finally:
        AUDIT_TMP.unlink(missing_ok=True)
    elapsed = time.time() - t0
    if proc.returncode != 0:
        print(f"ERROR: `lake env lean` failed ({proc.returncode}) after {elapsed:.0f}s:\n"
              + "".join(collected)[-8000:], file=sys.stderr)
        return 1
    print(f"kernel walk finished in {elapsed:.0f}s ({len(collected)} lines)")

    records, reported, errors, failed, manifest = parse_ga("".join(collected))
    if errors:
        print(f"ERROR: {len(errors)} declarations could not be audited "
              f"(a Lean panic or exception): {errors[:20]}", file=sys.stderr)
        return 1

    missing = [n for n in names if n not in records]
    if missing:
        print(f"ERROR: goal audit incomplete - no record for: {missing}", file=sys.stderr)
        return 1

    if reported is not None and reported != len(records):
        print(f"ERROR: Lean reported {reported} declarations, parsed {len(records)}",
              file=sys.stderr)
        return 1

    # A conjunct that never reported a spine means the `MetaM` walk failed for
    # that record; a half-read conjunct would silently become a `{}` claim shape.
    shapeless_conj = sorted(n for n, r in records.items()
                            if any(not c["spine"] or not c["head"] for c in r["conjuncts"]))
    if shapeless_conj:
        print(f"ERROR: conjuncts missing a head or a spine: {shapeless_conj[:20]}",
              file=sys.stderr)
        return 1

    # `headSyms` and `quant` are **derived**, never parsed: the display list is
    # the conjunct heads in order, and the record-level quantifier is whatever
    # the conjuncts agree on. Reading it off the goal's outer tag was wrong --
    # `tagOf` reports `app` for every `A ∧ B`, so 116 records claimed no
    # quantifier while one of their conjuncts was `∃`.
    for r in records.values():
        r["headSyms"] = [c["head"] for c in r["conjuncts"]]
        r["valueHeads"] = [c["head"] for c in r["valueConjuncts"]]
        quants = {c["quant"] for c in r["conjuncts"]}
        r["quant"] = (quants.pop() if len(quants) == 1
                      else "mixed" if quants else None)

    empty = [n for n, r in records.items()
             if not r["headSyms"] and not r["goal"] and r["kind"] not in ("def", "opaque")]
    if empty:
        print(f"ERROR: declarations with neither goal nor head symbols: {sorted(empty)}",
              file=sys.stderr)
        return 1

    # A truncated goal is fatal for a claim-bearing declaration: it is the
    # signature of a pretty-printer line break ending the emitted line, and the
    # loss is invisible downstream (the prefix still parses as a goal).
    cut = sorted((n, open_b) for n, r in records.items()
                 for open_b in [_truncated(r["goal"])]
                 if open_b and r["kind"] in ("thm", "axiom"))
    if cut:
        print(f"ERROR: {len(cut)} theorem/axiom goals are truncated (unbalanced "
              f"brackets) - the printed form was cut mid-expression: "
              f"{[n for n, _ in cut][:20]}", file=sys.stderr)
        return 1

    unprinted = sorted(n for n, r in records.items()
                       if not r["goal"] and r["kind"] not in ("def", "opaque"))
    if unprinted:
        print(f"note: {len(unprinted)} declarations report shape but no printed goal "
              f"(unreachable bound-variable level); first few: {unprinted[:5]}")

    # `(non-constant)` as a head is the reader shrugging, not a shape. It is
    # reported (not fatal) because a `def`'s peeled body can legitimately hold a
    # binder the audit does not name; `test_goal_audit.py` asserts it is absent
    # from every `thm`/`axiom`, which is the population that carries a claim.
    shrug = sorted(n for n, r in records.items()
                   if r["kind"] in ("thm", "axiom")
                   and any("(non-constant)" in (c["head"], c["spine"]) for c in r["conjuncts"]))
    if shrug:
        print(f"note: {len(shrug)} thm/axiom conjuncts are opaque "
              f"(head or spine is `(non-constant)`); first few: {shrug[:5]}")

    # `refs` are collected from the `Expr` in Lean, so this check needs no string
    # matching. The authority is the environment (`manifest`), NOT
    # `depgraph.json`: depviz omits model-local constants such as
    # `TheologicalModalHardening.GodAloneModel.Creates`, and a reference outside
    # the graph is a G1 countermodel signal rather than an error.
    env_names = set(manifest) or set(records)
    unknown = sorted({c for r in records.values() for c in r["refs"]} - env_names)
    if unknown:
        print(f"ERROR: Logos constants referenced but absent from the environment: "
              f"{unknown[:20]}", file=sys.stderr)
        return 1
    model_local = sorted({c for r in records.values() for c in r["refs"]} - graph_names)
    if model_local:
        print(f"note: {len(model_local)} referenced constants are model-local "
              f"(absent from depgraph.json) -- G1 countermodel signal; first few: "
              f"{model_local[:5]}")

    # Derived convenience field: basenames of the top-level conjunct heads.
    for r in records.values():
        r["headShorts"] = sorted({h.rsplit(".", 1)[-1] for h in r["headSyms"]})
    order = ("kind", "goal", "goalTag", "quant", "conjuncts", "headSyms", "headShorts",
             "valueConjuncts", "valueHeads", "boundSorts", "binderFree", "hypothesis", "refs")
    records = {n: {k: r[k] for k in order} for n, r in sorted(records.items())}

    OUT_PATH.write_text(json.dumps(records, indent=1, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    try:
        gfp.write_sidecar(len(records))
    except Exception as e:
        print(f"warn: could not write fingerprint sidecar: {e}", file=sys.stderr)
    print(f"wrote {OUT_PATH} ({len(records)} declarations, {failed} unrecoverable)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
